name: 'Test and Build'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Clean install dependencies
        run: npm ci

      - name: Run test eslint and prettier
        run: npm run test:lint

  build:
    env:
      VITE_WS_URL: ${{ secrets.VITE_WS_URL }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_NO_AVATAR_URL: ${{ secrets.VITE_NO_AVATAR_URL }}
      VITE_NO_BACKGROUND_URL: ${{ secrets.VITE_NO_BACKGROUND_URL }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Clean install dependencies
        run: npm ci

      - name: Run build
        run: npm run build
